in:
  type: facebook_ads_insights
  access_token: EAAFJl0feEY4BAF2BUhZBnmGqikyZCVJ8bO4DWR9ONjGcI03VhID6kjgGey1BR0Mdawh5xVZCmZBiH0WTnu749TT7OEW6l9FkLrmr2sDKePIBgaECvQ9fdeN0rTwJaepefFSdnf0gh8a9jr9mlqAerJQezUswuU2znBCWfNypJQZDZD
  object_type: account
  object_id: 2360215384296886
  fields:
    - {name: age, type: string}
    - {name: campaign_id, type: long}
    - {name: campaign_name, type: string}
    - {name: impressions, type: long}
    - {name: spend, type: double}
    - {name: actions, type: string}
out:
  type: stdout